version: '3'

services:
  web:
    build: .
    container_name: pmi-moscow-site
    restart: always
    expose:
      - "80"
      - "443"
    environment:
      - VIRTUAL_HOST=pmi.moscow,www.pmi.moscow,media.pmi.moscow
      - VIRTUAL_PORT=443
      - VIRTUAL_PROTO=https

networks:
  default:
    external:
      name: pmi_network